ERP/ERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('dashboard.urls')), # we link to the app dashboard
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('customers.urls')),
    path('', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ERP/customers/urls.py
from django.urls import path
from . import views


app_name = "customers"
urlpatterns = [
    path("customers/", views.customers, name="customers"),
    path("customers/new_customer/", views.new_customer, name="new_customer"),
    path("get_customer_info/<int:customer_id>/", views.get_customer_info, name="get_customer_info"),
    path("get_customer_details_drawer/<int:customer_id>/", views.get_customer_details_drawer, name="get_customer_details_drawer"),
]

ERP/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"
urlpatterns = [
    path('inventory/', views.inventory, name='inventory'),
    path('', views.dashboard, name='dashboard'),
    path('get_edit_drawer/<int:item_id>/', views.get_edit_drawer, name='get_edit_drawer'),
    path('create_item/', views.create_item_view, name='create_item'),
    path('datenschutz/', views.datenschutz_view, name='datenschutz'),
    path('impressum/', views.impressum_view, name='impressum'),
    path('nutzungsbedingungen/', views.nutzungsbedingungen_view, name='nutzungsbedingungen'),

]

ERP/orders/urls.py
from django.urls import path
from . import views


app_name = "orders"
urlpatterns = [
    path("orders", views.orders, name="orders"),
    path("new_order", views.new_order, name="new_order"),
    path("get_customer_info/<int:customer_id>/", views.get_customer_info, name="get_customer_info"),
    path("get_details_drawer/<int:order_id>/", views.get_details_drawer, name="get_details_drawer"),
]

ERP/templates/_base.html
{% load compress %}
{% load static %}
{% load django_browser_reload %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <!-- Add jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  {% compress css %}
  <link rel="stylesheet" href="{% static 'src/output.css' %}">
  {% endcompress %}

</head>

<body class="bg-indigo-50">
  <nav class="bg-indigo-300 border-indigo-200 dark:bg-indigo-900 w-full">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-indigo-50 text-indigo-950">
        <a href="{% url "dashboard:dashboard" %}">SIERP</a>
      </span>
      <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
        <button type="button"
          class="flex text-sm rounded-full md:me-0 focus:ring-4  dark:focus:ring-indigo-600 text-indigo-950"
          id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown"
          data-dropdown-placement="bottom">
          <link rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
          <span class="material-symbols-outlined">
            person
          </span>
        </button>
        <!-- Dropdown menu and stacked menu on mobile devices doesn't work jet maybe I need a different solution -->
        <div
          class="z-50 hidden my-4 text-base list-none divide-y divide-indigo-100 rounded-lg shadow dark:bg-indigo-700 dark:divide-indigo-600 bg-indigo-50"
          id="user-dropdown">
          <div class="px-4 py-3">
            <span class="block text-sm text-indigo-900 dark:text-white">Example User</span>
            <span class="block text-sm  text-indigo-500 truncate dark:text-indigo-400">name@sierp.com</span>
          </div>
          <ul class="py-2" aria-labelledby="user-menu-button">

          </ul>
        </div>
        <button data-collapse-toggle="navbar-user" type="button"
          class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-indigo-500 rounded-lg md:hidden hover:bg-indigo-100 focus:outline-none focus:ring-2 focus:ring-indigo-200 dark:text-indigo-400 dark:hover:bg-indigo-700 dark:focus:ring-indigo-600"
          aria-controls="navbar-user" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M1 1h15M1 7h15M1 13h15" />
          </svg>
        </button>
      </div>
      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
        <ul
          class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-indigo-100 rounded-lg bg-indigo-300 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0  dark:bg-indigo-800 md:dark:bg-indigo-900 dark:border-indigo-700">
          <li>
            <a href="{% url "dashboard:dashboard" %}"
              class="block py-2 px-3 text-indigo-900 rounded hover:bg-indigo-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-indigo-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-indigo-700"
              aria-current="page">Dashboard</a>
          </li>
          <li>
            <a href="{% url "dashboard:inventory" %}"
              class="block py-2 px-3 text-indigo-900 rounded hover:bg-indigo-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-indigo-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-indigo-700">Inventory</a>
          </li>
          <li>
            <a href="{% url "customers:customers" %}"
              class="block py-2 px-3 text-indigo-900 rounded hover:bg-indigo-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-indigo-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-indigo-700">Customers</a>
          </li>
          <li>
            <a href="{% url "orders:orders" %}"
              class="block py-2 px-3 text-indigo-900 rounded hover:bg-indigo-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-indigo-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-indigo-700">Orders</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="container mx-auto mt-4">
    {% block content %}
    {% endblock content %}
  </div>

  <div id="footer" class="bg-indigo-300 border-indigo-200 dark:bg-indigo-900 p-3 box justify-center mt-4 w-full">

    <footer class="max-w-screen-xl mx-auto py-4">

        
            <!-- Brand -->
            <div>
                <a class="text-xl font-semibold text-indigo-900 dark:text-sky-50 font-mono text-center" href="#"
                    aria-label="Brand">sinaihmels.dev</a>
            </div>
            <!-- End Brand -->

            <!-- Navigation -->
            <ul class="flex justify-center space-x-4 md:justify-end">
                <li>
                    <a class="text-sm text-indigo-500 hover:text-indigo-800 dark:text-indigo-500 dark:hover:text-indigo-200"
                        href="{% url "dashboard:datenschutz" %}">Datenschutzerklärung</a>
                </li>
                <li>
                    <a class="text-sm text-indigo-500 hover:text-indigo-800 dark:text-indigo-500 dark:hover:text-indigo-200"
                        href="{% url "dashboard:nutzungsbedingungen" %}">Nutzungsbedingungen</a>
                </li>
                <li>
                    <a class="text-sm text-indigo-500 hover:text-indigo-800 dark:text-indigo-500 dark:hover:text-indigo-200"
                        href="{% url "dashboard:impressum" %}">Impressum</a>
                </li>
            </ul>
            <!-- End Navigation -->
     
    </footer>

</div>


  <script type="module" src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
  {% block javascript %}
  {% endblock javascript %}

  {% django_browser_reload_script %}
</body>

</html>